.\"
.Dd September 2, 2015
.Dt RNDPASS 1
.Os
.Sh NAME
.Nm rndpassw
.Nd generate random passwords
.Sh SYNOPSIS
.Nm
.Op Fl dulpsvh
.Op Ar password length
.Op Ar password count
.Sh DESCRIPTION
The
.Nm
utility generates random passwords
.Pp
The following options are available:
.Bl -tag -width indent
.It Fl d
password contains numeric characters [0-9]
.It Fl u
password contains upper alpha characters [A-Z]
.It Fl l
password contains lower alpha characters [a-z]
.It Fl p
password contains printable charcaters
.It Fl s
password contains all previous characters groups
.It Fl v
print version
.It Fl h
print short usage
.Sh EXIT STATUS
.Ex -std
.Sh AUTHOR
Andrew Romanenko <melanhit@gmail.com>
.Sh SITE
https://github.com/melanhit/rndpassw
